iron:
  world: world
  x: 0
  y: 0
  z: 0
gold:
  world: world
  x: 0
  y: 0
  z: 0
diamond:
  world: world
  x: 0
  y: 0
  z: 0
lobby:
  world: world
  x: 0
  y: 0
  z: 0
  yaw: 0
  pitch: 0
red:
  world: world
  x: 0
  y: 0
  z: 0
  yaw: 0
  pitch: 0
blue:
  world: world
  x: 0
  y: 0
  z: 0
  yaw: 0
  pitch: 0