name: KojoGame
version: ${project.version}
main: koutachan.kojogame.KojoGame
commands:
  givestick:
    permission: kojogame.giveStick
  debug:
    permission: kojogame.debug
  start:
    permission: kojogame.start
  setspawn:
    permission: kojogame.setspawn
  team:
    permission: kojogame.team
  kojolist:
    usage: View teamlist
    aliases: team-list
  ping:
    usage: View Your Ping
    aliases: latency
  global:
    usage: Global Chat
    aliases: g
  grapple:
    permission: item.grapple
