name: KojoGame
version: ${project.version}
main: koutachan.kojogame.KojoGame
commands:
  givestick:
    permission: kojogame.giveStick
  debug:
    permission: kojogame.debug
  start:
    permission: kojogame.start
  setspawn:
    permission: kojogame.setspawn
  kojolist:
    aliases: team-list
  ping:
    aliases: latency
